rule tadpole:
    input:
        r1="{sample}.1.fq.gz",
        r2="{sample}.2.fq.gz",
        ref="contam_db.fa"
    output:
        r1="{sample}.ec.1.fq.gz",
        r2="{sample}.ec.2.fq.gz",
    log:
        "logs/bbsplit/{sample}.log"
    params:
        extra=""
    wrapper:
        "https://raw.githubusercontent.com/casperch/snakemake-wrappers/master/bio/bbmap/bbsplit"
