rule jellyfish_histo:
    input:
        "reads/a.1.fastq",
        "reads/a.2.fastq"
    output:
        "reads.histo"
    log:
        "logs/histo/histo.log"
    params:
        merlen=21,  # mer length
        hashsize="10G", # hashsize
        extra=""  # optional parameters
    threads: 16  # Use at least two threads
    wrapper:
        "file:///mnt/f/pipeline/snakemake-wrappers/bio/jellyfish/count_histo"
